# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7562435b1abdca42a7fb421e9297353a5d6dea97c1c37f67ab075d291c30d5b55a17698f3a6fca6208572e3d349c680970923f069f8fb8aeceb7ba959a8efe14

test:
  secret_key_base: 5b5e0e2e96a63ed83f44d331817b96c68b4ca1957c7243e05acce3ef15dd1e37bad95b7be488e2f7a9ca64f23a083301658e1a395393185735835c229853225c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
